[versions]
commons-io = "2.20.0"
jetbrains = "26.0.2-1"
systemlambda = "1.2.1"
testcontainers = "1.21.3"
vertx = "5.0.5"

plugin-jib = "3.5.1"
plugin-shadow = "9.2.2"

[libraries]
commons-io = { module = "commons-io:commons-io", version.ref = "commons-io" }
jetbrains-annotations = { module = "org.jetbrains:annotations", version.ref = "jetbrains" }
systemlambda = { module = "com.github.stefanbirkner:system-lambda", version.ref = "systemlambda" }
testcontainers-core = { module = "org.testcontainers:testcontainers", version.ref = "testcontainers" }
testcontainers-consul = { module = "org.testcontainers:consul", version.ref = "testcontainers" }
testcontainers-junit = { module = "org.testcontainers:junit-jupiter", version.ref = "testcontainers" }
vertx-consul = { module = "io.vertx:vertx-consul-client", version.ref = "vertx" }

[plugins]
jib = { id = "com.google.cloud.tools.jib", version.ref = "plugin-jib" }
shadow = { id = "com.gradleup.shadow", version.ref = "plugin-shadow" }
